add_newline = true 
format = """$directory$all"""
# right_format = """$all"""

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style)'

[docker_context]
disabled = true

[aws]
force_display = true
