version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    background = 'transparent'
    foreground = 'p:crystalBlue'
    template = '{{ .Path }}'

    [blocks.segments.properties]
      style = 'full'

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    foreground = 'p:springGreen'
    background = 'transparent'
    template = ' {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }} <p:dragonBlue>{{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }}</>'

    [blocks.segments.properties]
      branch_icon = ''
      commit_icon = '@'
      fetch_status = true

  [[blocks.segments]]
  type = "python"
  style = "plain"
  foreground = "p:carpYellow"
  background = "transparent"
  template = " {{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}{{ .Venv }} {{ end }}{{ .Full }}{{ end }}"

  [[blocks.segments]]
  type = "go"
  style = "plain"
  foreground = "dragonBlue"
  background = "transparent"
  template = " {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}"

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    type = 'executiontime'
    style = 'plain'
    foreground = 'p:fujiWhite'
    background = 'transparent'
    template = '{{ .FormattedMs }}'

    [blocks.segments.properties]
      threshold = 5000

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground_templates = [
      "{{if gt .Code 0}}p:samuraiRed{{end}}",
      "{{if eq .Code 0}}p:white{{end}}",
    ]
    background = 'transparent'
    template = '❯'

[transient_prompt]
  foreground_templates = [
      "{{if gt .Code 0}}p:samuraiRed{{end}}",
      "{{if eq .Code 0}}p:white{{end}}",
  ]
  background = 'transparent'
  template = '❯ '

[secondary_prompt]
  foreground = 'p:oldWhite'
  background = 'transparent'
  template = '❯❯ '

[palette]
sumiInk0 = "#16161D"
sumiInk1 = "#181820"
sumiInk2 = "#1a1a22"
sumiInk3 = "#1F1F28"
sumiInk4 = "#2A2A37"
sumiInk5 = "#363646"
sumiInk6 = "#54546D"

fujiWhite = "#DCD7BA"
oldWhite = "#C8C093"

samuraiRed = "#E82424"

waveBlue1 = "#223249"
waveBlue2 = "#2D4F67"
crystalBlue = "#7E9CD8"
dragonBlue = "#658594"

fujiGray = "#727169"

springGreen = "#98BB6C"

carpYellow = "#E6C384"
